work: Introduce reinstall-mn script

diff --git a/work/reinstall-mn b/work/reinstall-mn
--- a/work/reinstall-mn
+++ b/work/reinstall-mn
@@ -1,6 +1,8 @@
+#!/bin/bash
+
 # This file is a part of Scripts project
 #
-# Copyright (C) 2014, Alexander Kurbatov <sir.alkurbatov@yandex.ru>
+# Copyright (C) 2017, Alexander Kurbatov <sir.alkurbatov@yandex.ru>
 #
 # Scripts is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -16,11 +18,27 @@
 # along with this program. If not, see <http://www.gnu.org/licenses/>.
 
 # Purprose:
-# Completely restart PVA Agent on PCS node.
+# Completely reinstall Virtuozzo Automator Management Node
+# and clean up all required folders.
 
-#!/bin/bash
+yum groupremove -y 'VA Management Node' 'VA Control Center'
+yum remove -y va-cc-storage va-cc-i18n-ru va-docs
 
-service pvapp stop
-service pvaagentd restart
-service pvapp start
+rm -rf /etc/opt/pva/cc
+rm -rf /var/opt/pva
+rm -rf /var/log/pva
+rm -rf /opt/pva
+
+yum clean all
+yum groupinstall -y 'VA Management Node' 'VA Control Center'
+yum install -y va-cc-storage va-cc-i18n-ru va-docs
+
+for i in va-mn va-cc; do
+    systemctl start ${i}
+
+    if [ ${PIPESTATUS[0]} != 0 ]; then
+        echo "Failed to start ${i} service"
+        exit 1
+    fi
+done
 
